package dk.dma.niord.s100.xmlbindings.s124.v2_0_0.util;

/**
 * Plain carrier for the S-124 dataset identification fields. Sensible defaults for the
 * S-124 v2.0.0 / S-100 Part 10b encoding are pre-populated; callers may override any
 * field via the setters.
 */
public class S124DatasetInfo {

    private String datasetId;
    private String agency;
    private String encodingSpecification;
    private String encodingSpecificationEdition;
    private String productionIdentifier;
    private String productionEdition;
    private String fileIdentifier;
    private String title;
    private String language;
    private String abstractText;

    public S124DatasetInfo(String datasetId, String agency) {
        this.datasetId = datasetId;
        this.agency = agency;
        // The S-124 v2.0.0 XSD constrains this element to the literal "S-100 Part 10b".
        this.encodingSpecification = "S-100 Part 10b";
        this.encodingSpecificationEdition = "1.0";
        this.productionIdentifier = "S-124";
        this.productionEdition = "2.0.0";
        this.fileIdentifier = String.format("S-124_%s_%s", this.agency, this.datasetId);
        this.title = "S-124 Dataset";
        this.language = "en";
        this.abstractText = "Autogenerated S-124 Dataset";
    }

    public String getDatasetId() { return datasetId; }
    public void setDatasetId(String datasetId) { this.datasetId = datasetId; }
    public String getAgency() { return agency; }
    public void setAgency(String agency) { this.agency = agency; }
    public String getEncodingSpecification() { return encodingSpecification; }
    public void setEncodingSpecification(String encodingSpecification) { this.encodingSpecification = encodingSpecification; }
    public String getEncodingSpecificationEdition() { return encodingSpecificationEdition; }
    public void setEncodingSpecificationEdition(String encodingSpecificationEdition) { this.encodingSpecificationEdition = encodingSpecificationEdition; }
    public String getProductionIdentifier() { return productionIdentifier; }
    public void setProductionIdentifier(String productionIdentifier) { this.productionIdentifier = productionIdentifier; }
    public String getProductionEdition() { return productionEdition; }
    public void setProductionEdition(String productionEdition) { this.productionEdition = productionEdition; }
    public String getFileIdentifier() { return fileIdentifier; }
    public void setFileIdentifier(String fileIdentifier) { this.fileIdentifier = fileIdentifier; }
    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }
    public String getLanguage() { return language; }
    public void setLanguage(String language) { this.language = language; }
    public String getAbstractText() { return abstractText; }
    public void setAbstractText(String abstractText) { this.abstractText = abstractText; }
}
