package dk.dma.niord.s100.xmlbindings.s124.v2_0_0.util;

import java.math.BigInteger;
import java.time.LocalDate;
import java.time.ZoneOffset;

import dk.dma.niord.s100.xmlbindings.s100.gml.base._5_0.DatasetPurposeType;
import dk.dma.niord.s100.xmlbindings.s100.gml.base._5_0.MDTopicCategoryCode;

/**
 * Plain carrier for the S-124 dataset identification fields. Sensible defaults for the
 * S-124 v2.0.0 / S-100 Part 10b encoding are pre-populated; callers may override any
 * field via the setters.
 */
public class S124DatasetInfo {

    private String datasetId;
    private String agency;
    private String encodingSpecification;
    private String encodingSpecificationEdition;
    private String productionIdentifier;
    private String productionEdition;
    private String fileIdentifier;
    private String title;
    private String language;
    private String abstractText;
    private String applicationProfile;
    private LocalDate referenceDate;
    private MDTopicCategoryCode topicCategory;
    private DatasetPurposeType purpose;
    private BigInteger updateNumber;

    /**
     * @param datasetId the unique code of the dataset, used as the unique part of the
     *                  default file identifier
     * @param agency    the producer code of the issuing agency according to the IHO
     *                  Producer Code Register
     */
    public S124DatasetInfo(String datasetId, String agency) {
        this.datasetId = datasetId;
        this.agency = agency;
        // The S-124 v2.0.0 XSD constrains this element to the literal "S-100 Part 10b".
        this.encodingSpecification = "S-100 Part 10b";
        this.encodingSpecificationEdition = "1.0";
        this.productionIdentifier = "S-124";
        this.productionEdition = "2.0.0";
        this.fileIdentifier = defaultFileIdentifier(agency, datasetId);
        this.title = "S-124 Dataset";
        // ISO 639-2/T alpha-3 code: the datasetLanguage element is bound to the ISO-639-2
        // simple type, whose \w{3} pattern rejects 2-letter codes (S-100 Part 10b Table 10b-4).
        this.language = "eng";
        this.abstractText = "Autogenerated S-124 Dataset";
        // The remaining elements of DatasetIdentificationType are mandatory too: the
        // S-124 v2.0.0 XSD sequence rejects a dataset that omits any of them.
        this.applicationProfile = "NavigationalWarning";
        this.referenceDate = LocalDate.now(ZoneOffset.UTC);
        this.topicCategory = MDTopicCategoryCode.OCEANS;
        this.purpose = DatasetPurposeType.BASE;
        this.updateNumber = BigInteger.ZERO;
    }

    /**
     * Builds the default dataset file identifier following the naming pattern
     * XXXYYYYØØØØØØØØØ.[EXT] of S-100 Part 17 clause 17-4.3, which S-124 clause 9.7
     * mandates for dataset files: product code 124, the producer code, an alphanumeric
     * unique code and the GML encoding's file extension. Part 10b Table 10b-4 requires
     * the identifier to include the file extension.
     */
    private static String defaultFileIdentifier(String agency, String datasetId) {
        return String.format("124%s%s.GML", alphanumeric(agency), alphanumeric(datasetId));
    }

    private static String alphanumeric(String value) {
        return value == null ? "" : value.replaceAll("[^A-Za-z0-9]", "");
    }

    public String getDatasetId() { return datasetId; }
    public void setDatasetId(String datasetId) { this.datasetId = datasetId; }
    public String getAgency() { return agency; }
    public void setAgency(String agency) { this.agency = agency; }
    public String getEncodingSpecification() { return encodingSpecification; }
    public void setEncodingSpecification(String encodingSpecification) { this.encodingSpecification = encodingSpecification; }
    public String getEncodingSpecificationEdition() { return encodingSpecificationEdition; }
    public void setEncodingSpecificationEdition(String encodingSpecificationEdition) { this.encodingSpecificationEdition = encodingSpecificationEdition; }
    public String getProductionIdentifier() { return productionIdentifier; }
    public void setProductionIdentifier(String productionIdentifier) { this.productionIdentifier = productionIdentifier; }
    public String getProductionEdition() { return productionEdition; }
    public void setProductionEdition(String productionEdition) { this.productionEdition = productionEdition; }
    public String getFileIdentifier() { return fileIdentifier; }
    public void setFileIdentifier(String fileIdentifier) { this.fileIdentifier = fileIdentifier; }
    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }
    public String getLanguage() { return language; }
    public void setLanguage(String language) { this.language = language; }
    public String getAbstractText() { return abstractText; }
    public void setAbstractText(String abstractText) { this.abstractText = abstractText; }
    public String getApplicationProfile() { return applicationProfile; }
    public void setApplicationProfile(String applicationProfile) { this.applicationProfile = applicationProfile; }
    public LocalDate getReferenceDate() { return referenceDate; }
    public void setReferenceDate(LocalDate referenceDate) { this.referenceDate = referenceDate; }
    public MDTopicCategoryCode getTopicCategory() { return topicCategory; }
    public void setTopicCategory(MDTopicCategoryCode topicCategory) { this.topicCategory = topicCategory; }
    public DatasetPurposeType getPurpose() { return purpose; }
    public void setPurpose(DatasetPurposeType purpose) { this.purpose = purpose; }
    public BigInteger getUpdateNumber() { return updateNumber; }
    public void setUpdateNumber(BigInteger updateNumber) { this.updateNumber = updateNumber; }
}
