package dk.dma.niord.s100.xmlbindings.s124.v2_0_0.util;

import java.math.BigInteger;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.Objects;

import dk.dma.niord.s100.xmlbindings.s100.gml.base._5_0.DataSetIdentificationType;
import dk.dma.niord.s100.xmlbindings.s100.gml.base._5_0.DatasetPurposeType;
import dk.dma.niord.s100.xmlbindings.s100.gml.base._5_0.MDTopicCategoryCode;
import dk.dma.niord.s100.xmlbindings.s124.v2_0_0.Dataset;

/**
 * Plain carrier for the S-124 dataset identification fields. Sensible defaults for the
 * S-124 v2.0.0 / S-100 Part 10b encoding are pre-populated; callers may override any
 * field via the setters.
 */
public class S124DatasetInfo {

    /**
     * The application profile of a base dataset. S-100 Part 10b Table 10b-4 admits exactly
     * two values for the applicationProfile element of the dataset header: "1" for base
     * datasets and "2" for update datasets.
     */
    public static final String BASE_APPLICATION_PROFILE = "1";

    /** The application profile of an update dataset; see {@link #BASE_APPLICATION_PROFILE}. */
    public static final String UPDATE_APPLICATION_PROFILE = "2";

    private String datasetId;
    private String agency;
    private String encodingSpecification;
    private String encodingSpecificationEdition;
    private String productionIdentifier;
    private String productionEdition;
    private String fileIdentifier;
    private String title;
    private String language;
    private String abstractText;
    private String applicationProfile;
    private LocalDate referenceDate;
    private MDTopicCategoryCode topicCategory;
    private DatasetPurposeType purpose;
    private BigInteger updateNumber;

    /**
     * @param datasetId the unique code of the dataset, used as the unique part of the
     *                  default file identifier
     * @param agency    the producer code of the issuing agency according to the IHO
     *                  Producer Code Register
     */
    public S124DatasetInfo(String datasetId, String agency) {
        this.datasetId = datasetId;
        this.agency = agency;
        // The S-124 v2.0.0 XSD constrains this element to the literal "S-100 Part 10b".
        this.encodingSpecification = "S-100 Part 10b";
        this.encodingSpecificationEdition = "1.0";
        this.productionIdentifier = "S-124";
        this.productionEdition = "2.0.0";
        this.fileIdentifier = defaultFileIdentifier(agency, datasetId);
        this.title = "S-124 Dataset";
        // ISO 639-2/T alpha-3 code: the datasetLanguage element is bound to the ISO-639-2
        // simple type, whose \w{3} pattern rejects 2-letter codes (S-100 Part 10b Table 10b-4).
        this.language = "eng";
        this.abstractText = "Autogenerated S-124 Dataset";
        // The remaining elements of DatasetIdentificationType are mandatory too: the
        // S-124 v2.0.0 XSD sequence rejects a dataset that omits any of them.
        this.referenceDate = LocalDate.now(ZoneOffset.UTC);
        this.topicCategory = MDTopicCategoryCode.OCEANS;
        this.purpose = DatasetPurposeType.BASE;
        this.applicationProfile = applicationProfileFor(this.purpose);
        this.updateNumber = BigInteger.ZERO;
    }

    /**
     * The application profile that S-100 Part 10b Table 10b-4 pairs with a dataset purpose.
     * The XSD types applicationProfile as a free character string, so the constraint is
     * enforced here rather than by schema validation.
     */
    private static String applicationProfileFor(DatasetPurposeType purpose) {
        return purpose == DatasetPurposeType.UPDATE ? UPDATE_APPLICATION_PROFILE : BASE_APPLICATION_PROFILE;
    }

    /**
     * Builds the default dataset file identifier following the naming pattern
     * XXXYYYYØØØØØØØØØ.[EXT] of S-100 Part 17 clause 17-4.3, which S-124 clause 9.7
     * mandates for dataset files: product code 124, the producer code, an alphanumeric
     * unique code and the GML encoding's file extension. Part 10b Table 10b-4 requires
     * the identifier to include the file extension.
     * <p/>
     * Table 10b-4 makes this identifier the name of the file the dataset is packaged in,
     * so the agency must be the same producer code the exchange set is built with.
     */
    private static String defaultFileIdentifier(String agency, String datasetId) {
        return String.format("124%s%s.GML", alphanumeric(agency), alphanumeric(datasetId));
    }

    private static String alphanumeric(String value) {
        return value == null ? "" : value.replaceAll("[^A-Za-z0-9]", "");
    }

    public String getDatasetId() { return datasetId; }
    public void setDatasetId(String datasetId) { this.datasetId = datasetId; }
    public String getAgency() { return agency; }
    public void setAgency(String agency) { this.agency = agency; }
    public String getEncodingSpecification() { return encodingSpecification; }
    public void setEncodingSpecification(String encodingSpecification) { this.encodingSpecification = encodingSpecification; }
    public String getEncodingSpecificationEdition() { return encodingSpecificationEdition; }
    public void setEncodingSpecificationEdition(String encodingSpecificationEdition) { this.encodingSpecificationEdition = encodingSpecificationEdition; }
    public String getProductionIdentifier() { return productionIdentifier; }
    public void setProductionIdentifier(String productionIdentifier) { this.productionIdentifier = productionIdentifier; }
    public String getProductionEdition() { return productionEdition; }
    public void setProductionEdition(String productionEdition) { this.productionEdition = productionEdition; }
    public String getFileIdentifier() { return fileIdentifier; }
    public void setFileIdentifier(String fileIdentifier) { this.fileIdentifier = fileIdentifier; }
    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }
    public String getLanguage() { return language; }
    public void setLanguage(String language) { this.language = language; }
    public String getAbstractText() { return abstractText; }
    public void setAbstractText(String abstractText) { this.abstractText = abstractText; }
    public String getApplicationProfile() { return applicationProfile; }

    /**
     * Sets the application profile, and with it the dataset purpose it stands for. S-100
     * Part 10b Table 10b-4 defines only {@link #BASE_APPLICATION_PROFILE} and
     * {@link #UPDATE_APPLICATION_PROFILE}, and pairs each with a purpose, so the two
     * elements are one fact written twice: a header combining profile "2" with purpose
     * "base" contradicts itself, and the XSD - typing the element as a plain string -
     * would accept it. Any other value is rejected.
     */
    public void setApplicationProfile(String applicationProfile) {
        if (BASE_APPLICATION_PROFILE.equals(applicationProfile)) {
            this.purpose = DatasetPurposeType.BASE;
        } else if (UPDATE_APPLICATION_PROFILE.equals(applicationProfile)) {
            this.purpose = DatasetPurposeType.UPDATE;
        } else {
            throw new IllegalArgumentException(String.format(
                    "applicationProfile must be \"%s\" (base datasets) or \"%s\" (update datasets) "
                            + "(S-100 Part 10b Table 10b-4)",
                    BASE_APPLICATION_PROFILE, UPDATE_APPLICATION_PROFILE));
        }
        this.applicationProfile = applicationProfile;
    }
    public LocalDate getReferenceDate() { return referenceDate; }
    public void setReferenceDate(LocalDate referenceDate) { this.referenceDate = referenceDate; }
    public MDTopicCategoryCode getTopicCategory() { return topicCategory; }
    public void setTopicCategory(MDTopicCategoryCode topicCategory) { this.topicCategory = topicCategory; }
    public DatasetPurposeType getPurpose() { return purpose; }

    /**
     * Sets the dataset purpose, and with it the application profile that S-100 Part 10b
     * Table 10b-4 pairs with it: "1" for a base dataset and "2" for an update. The two
     * cannot be set apart, see {@link #setApplicationProfile(String)}.
     */
    public void setPurpose(DatasetPurposeType purpose) {
        // datasetPurpose is a mandatory element of DatasetIdentificationType, so a null
        // purpose would silently produce a dataset the S-124 XSD rejects.
        this.purpose = Objects.requireNonNull(purpose, "purpose must be base or update "
                + "(S-100 Part 10b Table 10b-4: datasetPurpose is mandatory)");
        this.applicationProfile = applicationProfileFor(purpose);
    }
    public BigInteger getUpdateNumber() { return updateNumber; }
    public void setUpdateNumber(BigInteger updateNumber) { this.updateNumber = updateNumber; }

    /**
     * Writes these fields into the dataset identification block of an S-124 dataset, replacing
     * whatever it held.
     * <p/>
     * Without this, the constraints this class enforces - above all the Table 10b-4 pairing of
     * {@code applicationProfile} with {@code datasetPurpose}, which the XSD types as a free string
     * and so cannot check - guarded nothing: a caller had no way to project a validated
     * {@code S124DatasetInfo} onto the {@code DataSetIdentificationType} a dataset actually
     * carries, and hand-populating that type bypassed every check here.
     *
     * @param dataset the dataset whose identification block is to be set; a dataset with none
     *                cannot be completed, so one is expected to be present
     */
    public void applyTo(Dataset dataset) {
        Objects.requireNonNull(dataset, "dataset is null");
        applyTo(Objects.requireNonNull(dataset.getDatasetIdentificationInformation(),
                "the dataset carries no datasetIdentificationInformation to populate"));
    }

    /** Writes these fields into the given dataset identification block. */
    public void applyTo(DataSetIdentificationType identification) {
        Objects.requireNonNull(identification, "identification is null");
        identification.setEncodingSpecification(encodingSpecification);
        identification.setEncodingSpecificationEdition(encodingSpecificationEdition);
        identification.setProductIdentifier(productionIdentifier);
        identification.setProductEdition(productionEdition);
        identification.setApplicationProfile(applicationProfile);
        identification.setDatasetFileIdentifier(fileIdentifier);
        identification.setDatasetTitle(title);
        identification.setDatasetReferenceDate(referenceDate);
        identification.setDatasetLanguage(language);
        identification.setDatasetAbstract(abstractText);
        identification.getDatasetTopicCategories().clear();
        identification.getDatasetTopicCategories().add(topicCategory);
        identification.setDatasetPurpose(purpose);
        identification.setUpdateNumber(updateNumber);
    }
}
