name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test
      run: mvn clean compile test --batch-mode

    - name: Verify JAXB Generation
      run: |
        # Check that JAXB generated sources exist
        ls -la s-100/src/main/generated/ || echo "No s-100 generated sources found"
        ls -la s-124/src/main/generated/ || echo "No s-124 generated sources found"
        
        # Count generated Java files
        S100_FILES=$(find s-100/src/main/generated -name "*.java" 2>/dev/null | wc -l || echo "0")
        S124_FILES=$(find s-124/src/main/generated -name "*.java" 2>/dev/null | wc -l || echo "0")
        
        echo "S-100 generated Java files: $S100_FILES"
        echo "S-124 generated Java files: $S124_FILES"
        
        # Verify we have generated files (should be > 0)
        if [ "$S100_FILES" -eq "0" ]; then
          echo "ERROR: No S-100 Java files generated"
          exit 1
        fi
        
        if [ "$S124_FILES" -eq "0" ]; then
          echo "ERROR: No S-124 Java files generated"
          exit 1
        fi
        
        echo "✅ JAXB generation successful"

    - name: Package
      run: mvn package -DskipTests --batch-mode

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jars
        path: |
          s-100/target/*.jar
          s-124/target/*.jar
        retention-days: 7